name: "[CI] Upstream latest - Buildah method Github Runner"

on:
  workflow_dispatch:
  push:
    paths:
      - 'Containerfile'
      - 'Containerfile.armv6'
      - '.github/workflows/container-build-stable-buildah.yml'
  schedule:
    - cron: '42 2 * * 6'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINERFILE_SUFFIX: ""

concurrency:
  group: '${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    steps:
    - name: Buildhah prepare
      run: |
        sudo apt update
        sudo apt install -y buildah podman
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Tar as root
      run: |
        sudo mv -fv /usr/bin/tar /usr/bin/tar.orig
        echo -e '#!/bin/sh\n\nsudo /usr/bin/tar.orig "$@"' | sudo tee -a /usr/bin/tar
        sudo chmod +x /usr/bin/tar

    - name: cache podman storage
      uses: actions/cache@v3
      with:
        path: ~/.local/share/containers/storage
        key: podman-storage-${{ matrix.platform }}

    - name: set upstream version
      run: |
        echo "UPSTREAM_BRANCH=$(curl -sSL https://api.github.com/repos/ancwrd1/snx-rs/releases/latest | grep tag_name | cut -d "\"" -f 4 | cut -d "v" -f2)" >>${GITHUB_ENV}

    - name: set lower case image_name
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ env.IMAGE_NAME }}'

    - name: Prepare armv6
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
        if [[ ${platform} == "linux/arm/v6" ]]; then echo "CONTAINERFILE_SUFFIX=.armv6" >> $GITHUB_ENV ; fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: export architecture name (removing os prefix)
      run: |
        echo "PODMAN_ARCH=${PLATFORM#*/}" >>${GITHUB_ENV}
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: Container meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}
        tags: |
          type=raw,value=build
        flavor: |
          suffix=-${{ env.PODMAN_ARCH }}

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ steps.meta.outputs.images }}
        build-args: snx_rs_version=${{env.UPSTREAM_BRANCH}}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        oci: true
        containerfiles: |
          ./Containerfile${{ env.CONTAINERFILE_SUFFIX }}
        platforms: ${{ matrix.platform }}

    - name: Container to tar
      # https://github.com/actions/runner-images/issues/10443#issuecomment-2296608244
      run: podman save -o /tmp/${{ env.PLATFORM_PAIR }}-oci.tar ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ env.PLATFORM_PAIR }}
        path: /tmp/${{ env.PLATFORM_PAIR }}-oci.tar
        if-no-files-found: error
        retention-days: 1

  upload:
    name: Upload images
    runs-on: leonardoamaral-github-runner-snx-rs-docker
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp
        pattern: build-*
        merge-multiple: true

    - name: set lower case image_name
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ env.IMAGE_NAME }}'

    - run: podman manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:manifest
    - run: |
        for container in /tmp/*.tar; do podman manifest add ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:manifest oci-archive:${container}; done

    - name: Container meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ env.UPSTREAM_BRANCH }}

    - name: add tags
      run: |
        # fix multi-line issue from steps.meta.outputs.tags
        podman tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:manifest $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' ')

    - name: Push image to GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}
        tags: ${{ steps.meta.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ${{ env.REGISTRY }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"

